version: '3.2'
services:
  gui:
    ports:
      - 5000:5000
    build:
      context: .
      args:
        CC_TEST_REPORTER_ID: ${CC_TEST_REPORTER_ID}
    volumes:
      - html:/release  
  selenium-server:
    image: selenium/standalone-chrome:3.14.0-gallium
    ports:
      - 4444:4444
    links:
      - gui
  codecept:
    build:
      context: ./codecept
    links:
      - selenium-server
volumes:
  html:
